// Classe criada para escolher os estados aleatórios, e outras informações caso necessário.
class chosenState {

  stateChosen(){
    const states = [
      {
         "id_state":"1",
         "id_country":"21",
         "id_zone":"2",
         "name":"Alabama",
         "iso_code":"AL",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"2",
         "id_country":"21",
         "id_zone":"2",
         "name":"Alaska",
         "iso_code":"AK",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"3",
         "id_country":"21",
         "id_zone":"2",
         "name":"Arizona",
         "iso_code":"AZ",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"4",
         "id_country":"21",
         "id_zone":"2",
         "name":"Arkansas",
         "iso_code":"AR",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"5",
         "id_country":"21",
         "id_zone":"2",
         "name":"California",
         "iso_code":"CA",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"6",
         "id_country":"21",
         "id_zone":"2",
         "name":"Colorado",
         "iso_code":"CO",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"7",
         "id_country":"21",
         "id_zone":"2",
         "name":"Connecticut",
         "iso_code":"CT",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"8",
         "id_country":"21",
         "id_zone":"2",
         "name":"Delaware",
         "iso_code":"DE",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"53",
         "id_country":"21",
         "id_zone":"2",
         "name":"District of Columbia",
         "iso_code":"DC",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"9",
         "id_country":"21",
         "id_zone":"2",
         "name":"Florida",
         "iso_code":"FL",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"10",
         "id_country":"21",
         "id_zone":"2",
         "name":"Georgia",
         "iso_code":"GA",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"11",
         "id_country":"21",
         "id_zone":"2",
         "name":"Hawaii",
         "iso_code":"HI",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"12",
         "id_country":"21",
         "id_zone":"2",
         "name":"Idaho",
         "iso_code":"ID",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"13",
         "id_country":"21",
         "id_zone":"2",
         "name":"Illinois",
         "iso_code":"IL",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"14",
         "id_country":"21",
         "id_zone":"2",
         "name":"Indiana",
         "iso_code":"IN",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"15",
         "id_country":"21",
         "id_zone":"2",
         "name":"Iowa",
         "iso_code":"IA",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"16",
         "id_country":"21",
         "id_zone":"2",
         "name":"Kansas",
         "iso_code":"KS",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"17",
         "id_country":"21",
         "id_zone":"2",
         "name":"Kentucky",
         "iso_code":"KY",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"18",
         "id_country":"21",
         "id_zone":"2",
         "name":"Louisiana",
         "iso_code":"LA",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"19",
         "id_country":"21",
         "id_zone":"2",
         "name":"Maine",
         "iso_code":"ME",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"20",
         "id_country":"21",
         "id_zone":"2",
         "name":"Maryland",
         "iso_code":"MD",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"21",
         "id_country":"21",
         "id_zone":"2",
         "name":"Massachusetts",
         "iso_code":"MA",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"22",
         "id_country":"21",
         "id_zone":"2",
         "name":"Michigan",
         "iso_code":"MI",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"23",
         "id_country":"21",
         "id_zone":"2",
         "name":"Minnesota",
         "iso_code":"MN",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"24",
         "id_country":"21",
         "id_zone":"2",
         "name":"Mississippi",
         "iso_code":"MS",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"25",
         "id_country":"21",
         "id_zone":"2",
         "name":"Missouri",
         "iso_code":"MO",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"26",
         "id_country":"21",
         "id_zone":"2",
         "name":"Montana",
         "iso_code":"MT",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"27",
         "id_country":"21",
         "id_zone":"2",
         "name":"Nebraska",
         "iso_code":"NE",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"28",
         "id_country":"21",
         "id_zone":"2",
         "name":"Nevada",
         "iso_code":"NV",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"29",
         "id_country":"21",
         "id_zone":"2",
         "name":"New Hampshire",
         "iso_code":"NH",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"30",
         "id_country":"21",
         "id_zone":"2",
         "name":"New Jersey",
         "iso_code":"NJ",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"31",
         "id_country":"21",
         "id_zone":"2",
         "name":"New Mexico",
         "iso_code":"NM",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"32",
         "id_country":"21",
         "id_zone":"2",
         "name":"New York",
         "iso_code":"NY",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"33",
         "id_country":"21",
         "id_zone":"2",
         "name":"North Carolina",
         "iso_code":"NC",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"34",
         "id_country":"21",
         "id_zone":"2",
         "name":"North Dakota",
         "iso_code":"ND",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"35",
         "id_country":"21",
         "id_zone":"2",
         "name":"Ohio",
         "iso_code":"OH",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"36",
         "id_country":"21",
         "id_zone":"2",
         "name":"Oklahoma",
         "iso_code":"OK",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"37",
         "id_country":"21",
         "id_zone":"2",
         "name":"Oregon",
         "iso_code":"OR",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"38",
         "id_country":"21",
         "id_zone":"2",
         "name":"Pennsylvania",
         "iso_code":"PA",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"51",
         "id_country":"21",
         "id_zone":"2",
         "name":"Puerto Rico",
         "iso_code":"PR",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"39",
         "id_country":"21",
         "id_zone":"2",
         "name":"Rhode Island",
         "iso_code":"RI",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"40",
         "id_country":"21",
         "id_zone":"2",
         "name":"South Carolina",
         "iso_code":"SC",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"41",
         "id_country":"21",
         "id_zone":"2",
         "name":"South Dakota",
         "iso_code":"SD",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"42",
         "id_country":"21",
         "id_zone":"2",
         "name":"Tennessee",
         "iso_code":"TN",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"43",
         "id_country":"21",
         "id_zone":"2",
         "name":"Texas",
         "iso_code":"TX",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"52",
         "id_country":"21",
         "id_zone":"2",
         "name":"US Virgin Islands",
         "iso_code":"VI",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"44",
         "id_country":"21",
         "id_zone":"2",
         "name":"Utah",
         "iso_code":"UT",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"45",
         "id_country":"21",
         "id_zone":"2",
         "name":"Vermont",
         "iso_code":"VT",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"46",
         "id_country":"21",
         "id_zone":"2",
         "name":"Virginia",
         "iso_code":"VA",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"47",
         "id_country":"21",
         "id_zone":"2",
         "name":"Washington",
         "iso_code":"WA",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"48",
         "id_country":"21",
         "id_zone":"2",
         "name":"West Virginia",
         "iso_code":"WV",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"49",
         "id_country":"21",
         "id_zone":"2",
         "name":"Wisconsin",
         "iso_code":"WI",
         "tax_behavior":"0",
         "active":"1"
      },
      {
         "id_state":"50",
         "id_country":"21",
         "id_zone":"2",
         "name":"Wyoming",
         "iso_code":"WY",
         "tax_behavior":"0",
         "active":"1"
      }
    ];


    const numero = Math.floor(Math.random() * states.length); // é gerado um numero aleatório conforme o tamanho do array
    return states[numero];
  }
  

}

export default new chosenState();